(shared) updated jason-databind version from 2.9.7 to 2.9.8 due to se…
Altinn/fdk pull request #1166
Opened 2019-01-16 08:56 UTC by bgrova

Oppdatering av jason-databind fra versjon 2.9.7 til 2.9.8 av pga sikkerhetsadvarsel fra Github.

2019-01-16 10:38 UTC, markkopaas requested changes
veldig interessant - hvorfor maven tab viser at vi bruker 2.9.6 i registration-auth og registration-api?

2019-01-16 15:42 UTC, bgrova commented
Spring boot tok med seg en avhengighet til jackson-databind. Måtte derfor oppgradere til spring boot 2.0.8.
Fikk ikke til å "resolve" kommentaren. Tror det er pga at jeg tok en force commit.

2019-01-16 15:42 UTC, bgrova commented
Har lagt til Jira-sak: API-820

2019-01-16 18:42 UTC, markkopaas approved these changes

2019-01-17 12:40 UTC, markkopaas approved these changes

2019-01-17 12:40 UTC, merged