feat (search) add tab Structure to information details page and parse…
Altinn/fdk pull request #1199
Opened 2019-01-22 13:18 UTC by oyvindis

… schema

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-01-22 13:31 UTC, markkopaas requested changes

2019-01-22 13:31 UTC, markkopaas commented on applications/search/src/mock/informationmodelApiResponse.json
> +            "$ref": "#/components/schemas/Aarstall"
du skal få #/definitions/xxx  i stedet av #/components/schemas/xxx, så du kunne gjøre find-replace og være litt mer realistisk

2019-01-23 14:06 UTC, markkopaas requested changes

2019-01-23 14:06 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/information-model-details-page.jsx
> +const renderStructure = definitions => {
det ser ut som en veldig selvstendig render funksion, kunne være i sit eget fil som stateless component. er det StructureTab? eller egentlig bare Structure, fordi page tar vare av tab fordi, "Structure" er jo. innehold av en Tab

2019-01-23 14:06 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/information-model-details-page.jsx
> +      schemaString = parseSchema(items[key], schemaString, nestLevel, key);
interessant, vanligvis string er input til "parse" og output er noe strukturert.
men du bruker den variable senere til rendering. så kanskje passende navn kunne være "renderSchema"?

2019-01-23 14:06 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/information-model-details-page.jsx
> +  const schemaItems = items =>
kanskje den funksjon skulle ha prefix "render"?

2019-01-23 14:06 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/schema-collapse/schema-item/schema-items.component.jsx
> +  type: PropTypes.oneOfType([
dekker object ikke alle?

2019-01-24 07:06 UTC, oyvindis commented on applications/search/src/mock/informationmodelApiResponse.json
> +            "$ref": "#/components/schemas/Aarstall"
fixed

2019-01-24 07:19 UTC, oyvindis commented on applications/search/src/pages/informationmodel-details-page/information-model-details-page.jsx
> +const renderStructure = definitions => {
fixed

2019-01-24 07:20 UTC, oyvindis commented on applications/search/src/pages/informationmodel-details-page/information-model-details-page.jsx
> +  const schemaItems = items =>
fixed

2019-01-24 07:23 UTC, oyvindis commented on applications/search/src/pages/informationmodel-details-page/information-model-details-page.jsx
> +      schemaString = parseSchema(items[key], schemaString, nestLevel, key);
rettet

2019-01-24 07:23 UTC, oyvindis commented on applications/search/src/pages/informationmodel-details-page/schema-collapse/schema-item/schema-items.component.jsx
> +  type: PropTypes.oneOfType([
nei, fikk warning på det.

2019-01-24 09:03 UTC, markkopaas approved these changes

2019-01-24 09:03 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/schema-collapse/schema-item/schema-items.component.jsx
> +  type: PropTypes.oneOfType([
a, kanskje de har "any" da? men du er helt helt sikkert at det er lurt å ha varienrende typ? kanskje bruk children? i stedet?

2019-01-24 09:03 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/information-model-details-page.jsx
> +          {
du har her også teoretisk mulighet (kanskje framtid?) til å bruke children i stedet av props
`
<Tabs>
     <Tab title="fafafa">
          <Structure/>
....
`

2019-01-24 09:03 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/schemas/schemas.component.jsx
> +function resolveReferencedType(schema, type) {
navn "resolve" minner ikke noe om ui-relatert. Kanskje du ville separere ut resolve-del og render del fra den funksjon?

datastrukturmanipulasjoner kan godt være gjort i en lib module.

2019-01-24 09:03 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/schemas/schemas.component.jsx
> +  const resolvedType = [];
array skulle ha flertall navn

2019-01-24 09:03 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/schemas/schemas.component.jsx
> +            const type = /[^/]+$/.exec(item[itemKey])[0];
tar litt tid å lese regex....

s.substring(s.lastIndexOf('/')+1)

det er enda værre, fordi her bruker vi magi, ag lastIndexOf gir -1 hvis ikke finnes...

2019-01-24 09:03 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/schemas/schemas.component.jsx
> +      !Array.isArray(schema[key]) &&
kan du ekstrahere inneholdene alle if-delene som navnet funksjoner? den hele funksjon er alt for langt.

2019-01-24 09:03 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/schemas/schemas.component.jsx
> +      <SchemaCollapseWithState
er det noe nytt? du har ikke lagt det i denne kommit, så du skulle kanskje ikke fikse det heller, men snakket vi ikke at stateful komponenter skulle få en naturlig alias eksportert?
SchemaCollapsePure=...
SchemaCollapse=SchemaCollapseWithState=enhance(SchemaCollapsePure)

2019-01-25 12:57 UTC, markkopaas requested changes

2019-01-25 12:57 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component-property/model-component-property.component.jsx
> +  if (!(name || type || typeRef)) {
ganske interessant, er det mulig å render uten name, med bare type? 

Det skulle være teoretisk mulig å ha property uten ingen av de tre typ-varianter  (type, typeRef, oneOfTyperefs), da rendrer vi bare name

lang historie, men jeg mente`if (!(name)` skulle være nok

2019-01-25 12:57 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component-property/model-component-property.component.jsx
> +  if (oneOfTypeRefs) {
native typer er i "type" property, det skulle være tredje case her

2019-01-25 12:57 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component-property/model-component-property.component.jsx
> +        {(typeRefArray.length > 0 ? typeRefArray : null) || type}
jeg anbefaler å samle array av data (uten render | inni data)
og her, i render blokk, har to altenariver. 
typeArray.length>1?( "("+typeArray.join('|')+")") : typeArray[0]

jeg vet ikke hvis det er lovlig i react :) fordi din typeArray er jo rendering.komponenter...
Får man ikke key error, hvis du render en array?


kanskje enkleste er til å separe de tre scenarioer til hver sit eget små funksjon. og ta vare et array av 1 item er samme som en...

også, det er kanskje godt mulig at oneOfTypeRefs er faktisk array av native typer (det kan være at min konversionfunksjon har ikke den variant dekket...

2019-01-25 12:57 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component.component.jsx
> +  return Object.keys(properties).map(key => {
I stedet af object.keys().map, kan man bruke  https://lodash.com/docs/4.17.11#mapValues

_.mapValues(obj, (key,value,obj)=>{}) 

du sparer ingen linjen med dette :)

2019-01-25 12:57 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component.component.jsx
> +    if (typeRef) {
glemte du tredje mulighet, "type"?

2019-01-25 12:57 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component.component.jsx
> +    const resolvedTypes = [];
er det i bruk??

2019-01-25 12:57 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component.component.jsx
> +      <ModelComponentProperty
du kan jo gi den property objekt selv, til ModelCompoenntProperty renderer. eller navn+property (fordi property inneholder ikke navn. kanskje vi skulle ha navn inni der, bare til å spare parametrer) 
Da er det mer slik "tuple" logikk, eller "record"

2019-01-25 12:57 UTC, markkopaas commented on applications/search/src/pages/informationmodel-details-page/structure/structure.component.jsx
> +      <ModelComponent name={key} definitions={definitions} />
i lib, vi nå bruker jo root schema, hva er det du kan gjøre med definitions?

2019-01-25 13:33 UTC, oyvindis commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component-property/model-component-property.component.jsx
> +  if (!(name || type || typeRef)) {
rettet

2019-01-25 13:56 UTC, oyvindis commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component-property/model-component-property.component.jsx
> +  if (oneOfTypeRefs) {
rettet

2019-01-25 14:00 UTC, oyvindis commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component.component.jsx
> +    if (typeRef) {
det var duplikat her fra mode-component-property, fjernet denne.

2019-01-25 14:01 UTC, oyvindis commented on applications/search/src/pages/informationmodel-details-page/model-component/model-component.component.jsx
> +    const resolvedTypes = [];
nei, samme som forrige, fjernet

2019-01-25 14:26 UTC, markkopaas approved these changes

2019-01-25 14:29 UTC, merged