Refactor/mp/imharvestsource
Altinn/fdk pull request #1219
Opened 2019-01-29 10:56 UTC by markkopaas

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-01-29 11:10 UTC, thomasnokleby commented on applications/informationmodel-cat/src/main/java/no/fdk/imcat/service/InformationmodelHarvester.java
> +        //At the moment we only apiRegistrationsHarvest our own apis.
?

2019-01-29 11:14 UTC, thomasnokleby requested changes
Det er ikke nødvendig å fjerne source type implementation

2019-01-29 11:17 UTC, markkopaas commented on applications/informationmodel-cat/src/main/java/no/fdk/imcat/service/InformationmodelHarvester.java
> +        //At the moment we only apiRegistrationsHarvest our own apis.
IntelliJ gikk lit ut av kontrol:) takk!

2019-01-29 11:43 UTC, markkopaas commented
Du er rett at det er ikke noe hastighet til å fjerne det. Jeg skal la det være inntil videre.

2019-01-29 11:50 UTC, thomasnokleby approved these changes
Ok!

2019-01-30 08:39 UTC, thomasnokleby approved these changes

2019-01-30 08:40 UTC, merged