feat (registration-react) API-893 update api specification
Altinn/fdk pull request #1269
Opened 2019-02-07 09:37 UTC by oyvindis

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-02-07 11:26 UTC, markkopaas requested changes

2019-02-07 11:26 UTC, markkopaas commented on applications/registration-react/src/api/patch-api-file.js
> +export const patchApiFile = (catalogId, apiId, apiSpec) => {
hforfor ikke ha en generell patch method? som sender videre gitt payload?
```
import { patch } from 'axios';

 export const patchApi = (catalogId, apiId, body) => {
  const url = `/catalogs/${catalogId}/apis/${apiId}`;

   return patch(url, body).then(response => response.data);
};
```

2019-02-07 11:26 UTC, markkopaas commented on applications/registration-react/src/pages/api-registration-page/api-registration-page.jsx
> +export const APIRegistrationPagePure = props => {
det kunne være enklere å følge, hvis slik ting er i separat commit

2019-02-07 11:26 UTC, markkopaas commented on applications/registration-react/src/redux/modules/apis.js
> +    case APIS_UPDATE_ITEM:
kanskje det er bedre å ha get action i stedet?
eller response action (fordi get, patch og update alle svarer entity, så alle de egentlig skulle generere samme success action )

2019-02-07 11:35 UTC, markkopaas commented on applications/registration-react/src/api/patch-api-file.js
> +  const url = `/catalogs/${catalogId}/apis/${apiId}`;
også, siden alle REST endepunkter deler samme url, da er det lurt å samle metodimplementasjon.
se hvordan i search vi har samlemt alle 'apis' resource endepunkter inni samme fil, så at url er definert felles

2019-02-07 13:20 UTC, oyvindis commented on applications/registration-react/src/redux/modules/apis.js
> +    case APIS_UPDATE_ITEM:
jeg vet ikke om jeg skjønner, mener du endre navnet?

2019-02-08 11:34 UTC, markkopaas commented on applications/registration-react/src/redux/modules/apis.js
> +    case APIS_UPDATE_ITEM:
til listen av apis, du har følgende action:
export const APIS_REQUEST = 'APIS_REQUEST';
export const APIS_SUCCESS = 'APIS_SUCCESS';
export const APIS_FAILURE = 'APIS_FAILURE';

til enkel item operasjoner, har du følgende action:
export const APIS_ADD_ITEM = 'APIS_ADD_ITEM';
export const APIS_ITEM_SET_STATUS = 'APIS_ITEM_SET_STATUS';
export const APIS_ITEM_DELETE = 'APIS_ITEM_DELETE';

mitt anbefaling, er at de action som er om sender http request, skulle ha suffix _REQUEST 
e.g. APIS_ITEM_DELETE_REQUEST, vi har ikke enkel api item get, men det kunne være APIS_ITEM_REQUEST, eller API_REQUEST (da skulle vi også ha API_DELETE_REQUEST)
Så http requestene får svar. Vi har ett eksempel - APIS_REQUEST -> APIS_SUCCESS. På samme møte skulle du ha API_REQUEST og API_SUCCESS.

Og siden til POST, PUT og PATCH , vi har bestemt å svare entity, da kunne de gjenbruke samme action - API_SUCCESS. Den action sier til redux at vi har oppdatert nytt entity innehold.

Så mitt forslag er, å ha en før-refaktorering commit som endrer APIS_ITEM_SET_STATUS (som kommer fra form patch response) til API_SUCCESS

så hva gjenstår i dette kommit her, er bare patch actioncreator (som generer API_PATCH_REQUEST, men svarer med felles API_SUCCESS)


og nå fant jeg også en feil -

2019-02-11 09:52 UTC, oyvindis commented on applications/registration-react/src/redux/modules/apis.js
> +    case APIS_UPDATE_ITEM:
Rettet

2019-02-11 09:53 UTC, oyvindis commented on applications/registration-react/src/api/patch-api-file.js
> +  const url = `/catalogs/${catalogId}/apis/${apiId}`;
Rettet

2019-02-12 07:35 UTC, markkopaas requested changes

2019-02-12 07:35 UTC, markkopaas commented on applications/registration-react/src/pages/api-registration-page/api-registration-page.jsx
> +const renderApiSpecificationInfo = (
hvis du brukte object decomposition, reduserte du risk av parameter rekkefølge. Jeg anbefaler det hvis du har mer en 2 parameter

2019-02-12 07:35 UTC, markkopaas commented on applications/registration-react/src/pages/api-registration-page/import-dialog/import-dialog.component.jsx
> +    catalogId,
det er ikke nødvendig å bruke parameter props, du kan gjøre decomposition rett i argumentlinje, hvis du vil.

2019-02-12 07:35 UTC, markkopaas commented on applications/registration-react/src/pages/api-registration-page/import-dialog/import-dialog.component.jsx
> +          console.log('error', error); // eslint-disable-line no-console
en dag vi må implementere logging abstraksjon. ehkleste - den hele catch innehold skulle være '.catch(errrorhandler)'
og errorhandler er lib funksjon. ( i separat commit :D )

2019-02-12 07:48 UTC, oyvindis commented on applications/registration-react/src/pages/api-registration-page/api-registration-page.jsx
> +const renderApiSpecificationInfo = (
Ja, lurt! Rettet.

2019-02-12 07:55 UTC, oyvindis commented on applications/registration-react/src/pages/api-registration-page/import-dialog/import-dialog.component.jsx
> +    catalogId,
Endret

2019-02-12 12:33 UTC, markkopaas approved these changes

2019-02-14 09:11 UTC, merged