Feature/tno/harvest concepts from difi
Altinn/fdk pull request #1271
Opened 2019-02-07 13:09 UTC by thomasnokleby

API-906

2019-02-07 13:25 UTC, markkopaas requested changes

2019-02-07 13:25 UTC, markkopaas commented on applications/concept-cat/src/main/java/no/ccat/service/ConceptHarvester.java
> +    private HarvestURIList harvestURIList;
Skulle ikke autowire begge preperty og constructor
Grunnen til å ha alle autowire i tjeneste constructor argurments, er at da kan vi unngå bruk av spring i unit test - vi kan bare gi mock som argument til constructor.

2019-02-07 13:25 UTC, markkopaas commented on applications/concept-cat/src/main/java/no/ccat/service/ConceptHarvester.java
> +    public ConceptHarvester(ConceptDenormalizedRepository conceptDenormalizedRepository, RDFToModelTransformer rdfToModelTransformer, HarvestURIList harvestURIList) {
Alternativt, du kunne lese konfigurasjon value også her i construction parameter med `@Value` decorator, uten injection og configuration-class.

2019-02-07 13:25 UTC, markkopaas commented on applications/concept-cat/src/main/java/no/ccat/service/ConceptHarvester.java
> +        String theEntireDocument = readURLFully(harvestUri);
Ikke bruke engelsk artikler i variablenavn.

2019-02-07 13:33 UTC, thomasnokleby commented on applications/concept-cat/src/main/java/no/ccat/service/ConceptHarvester.java
> +    public ConceptHarvester(ConceptDenormalizedRepository conceptDenormalizedRepository, RDFToModelTransformer rdfToModelTransformer, HarvestURIList harvestURIList) {
Value støtter ikke komplekse typer.

2019-02-08 10:41 UTC, thomasnokleby commented on applications/concept-cat/src/main/java/no/ccat/service/ConceptHarvester.java
> +    private HarvestURIList harvestURIList;
Ah self! Takk :)

2019-02-08 11:11 UTC, markkopaas approved these changes

2019-02-08 11:24 UTC, merged