Fix/mp/apiregpatch
Altinn/fdk pull request #1295
Opened 2019-02-13 21:44 UTC by markkopaas

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-02-14 13:05 UTC, thomasnokleby commented on applications/registration-api/src/main/java/no/dcat/model/ApiRegistrationFactory.java
> +        updates.entrySet().stream()
Mangler en kommentar her. Er det det du faktisk gjør at du populerer JSON treet med verdiene fra updates ?

2019-02-14 13:08 UTC, thomasnokleby commented on applications/registration-api/src/main/java/no/dcat/model/ApiRegistrationFactory.java
> +
Det er mest sannsynlig bedre, og mer i tråd med kanonisk kode å bruke en copy construktor og en 
ApiRegistration apply(ApiRegistration incomingApiRegistrationWithChanges)
eller en 
ApiRegistration apply(Map<String, Object> incomingMapWithChanges).

Som returnerer en oppdatert ApiRegistration.

2019-02-14 13:13 UTC, thomasnokleby requested changes
Se kommentar

2019-02-19 23:10 UTC, markkopaas commented
Replaced with #1330

2019-02-19 23:10 UTC, closed without merging