Feature/tno/harvest alt inn30 apis
Altinn/fdk pull request #1451
Opened 2019-02-27 07:30 UTC by thomasnokleby

Denne koden har en oppdatert i formationmodel-cat, som da leser altinn apiene, og høster dem. Jeg har kommentert ut høstingen av vår egne apier. Merk at altinn-høstingen tar ca 5 min, og det ser ut som om det feiler stille, men det kommer. 

For øyeblikket høstes bare schema for tjenestens hovedskjema, ikke underskjermaer, om tjenesten har flere skjema. 

Problemet mitt er at selv om jeg klarer å kalle informationmodel-cat direkte, får jeg ikke dette til å virke i søkeløsningen min lokalt (tab som skal vise tall viser bare ingenting, og en får ikke opp noen informasjonsmodeller)

2019-02-28 12:43 UTC, bgrova requested changes

2019-02-28 12:43 UTC, bgrova commented on applications/informationmodel-cat/src/main/java/no/fdk/imcat/service/AltinnHarvest.java
> +    private static String harvestSourceURIBase = "https://fdk-dev-altinn.appspot.com/api/v1/schemas/";
burde dette helle vært en property? Kan det være at vi får både dev- og prod-variant av denne?

2019-02-28 12:45 UTC, thomasnokleby commented on applications/informationmodel-cat/src/main/java/no/fdk/imcat/service/AltinnHarvest.java
> +    private static String harvestSourceURIBase = "https://fdk-dev-altinn.appspot.com/api/v1/schemas/";
Ja, du har helt rett. Bør være en property (selv om vi p.t bare har et environment på denne).

2019-03-01 13:34 UTC, thomasnokleby commented on applications/informationmodel-cat/src/main/java/no/fdk/imcat/service/AltinnHarvest.java
> +    private static String harvestSourceURIBase = "https://fdk-dev-altinn.appspot.com/api/v1/schemas/";
Da er dette en property!

2019-03-04 11:55 UTC, merged