Feature/ois/api 1411 reg api
Altinn/fdk pull request #1487
Opened 2019-03-07 13:49 UTC by oyvindis

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-03-07 16:12 UTC, markkopaas requested changes

2019-03-07 16:12 UTC, markkopaas commented on applications/registration-react/src/pages/dataset-registration-page/form-distribution/form-distribution.component.jsx
> +          if (_.get(initialValues, ['distribution', index, 'accessService'])) {
den logikkendring er ikke beskrevd i commitmelding. kan du gjøre det i eget commit?
I tillegg det ser ikke ut veldig logisk - hvorfor ikke render hvis ting finnes?

2019-03-07 16:12 UTC, markkopaas commented on applications/registration-react/src/pages/dataset-registration-page/form-distribution/form-distribution.component.jsx
> +                  title={
Du har flere lintingfix i denne commit. Kan du finne en måte hvordan å ha linting i sitt eget commit?

2019-03-07 16:12 UTC, markkopaas commented on applications/registration-react/src/api/apis.js
> +  aggregations = true,
jeg har endret den kode som du koperte fra i den andre bransjen. kan du sjekke.

2019-03-08 08:07 UTC, markkopaas commented
Du burde prøve å kjøre release skripten og se hvis dit kommit kommt inni changelog. Jeg tror ikke.

2019-03-08 08:43 UTC, oyvindis commented on applications/registration-react/src/pages/dataset-registration-page/form-distribution/form-distribution.component.jsx
> +          if (_.get(initialValues, ['distribution', index, 'accessService'])) {
rettet i egen commit med kommentar

2019-03-08 08:44 UTC, oyvindis commented on applications/registration-react/src/api/apis.js
> +  aggregations = true,
Jeg skjønner ikke hva som er endret? Hvor skal jeg sjekke?

2019-03-08 08:48 UTC, oyvindis commented on applications/registration-react/src/pages/dataset-registration-page/form-distribution/form-distribution.component.jsx
> +                  title={
rettet

2019-03-08 08:56 UTC, markkopaas commented on applications/registration-react/src/api/apis.js
> +  aggregations = true,
Se getDatasetByTitlePrefix  (i develop, akkurat merget)
siden aggregeringer kommer ikke som default, du trenger ikke dette parameter

2019-03-08 09:09 UTC, oyvindis commented on applications/registration-react/src/api/apis.js
> +  aggregations = true,
rettet

2019-03-08 09:19 UTC, markkopaas approved these changes

2019-03-08 11:15 UTC, merged