feat(search-api): #1414 Add new aggregations to dataset search: distO…
Altinn/fdk pull request #1495
Opened 2019-03-08 09:28 UTC by markkopaas

…nNonPublicAccessCount,nonDistOnPublicAccessCount,nonDistOnNonPublicAccessCount

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-03-08 11:08 UTC, thomasnokleby commented on applications/search-api/src/main/java/no/fdk/searchapi/controller/DatasetsSearchController.java
> +        if (selectedAggregationFields.contains("distOnNonPublicAccessCount")) {
Hva står distOnNonPublic for  ?

2019-03-08 11:08 UTC, thomasnokleby commented on applications/search-api/src/main/java/no/fdk/searchapi/controller/DatasetsSearchController.java
> +        if (selectedAggregationFields.contains("nonDistOnPublicAccessCount")) {
Hva står nonDistOn for  ?

2019-03-08 11:09 UTC, thomasnokleby commented on applications/search-api/src/main/java/no/fdk/searchapi/controller/DatasetsSearchController.java
> +        if (selectedAggregationFields.contains("nonDistOnNonPublicAccessCount")) {
Som over

2019-03-08 11:09 UTC, thomasnokleby requested changes
Trenger enten en forklarende kommentar eller et mindre forkortet variabelnavn.

2019-03-08 11:22 UTC, oyvindis approved these changes

2019-03-12 08:35 UTC, thomasnokleby approved these changes
Ser bra ut!

2019-03-12 09:14 UTC, merged