chore(registration-react): add formHandlerDatasetPatch and update all…
Altinn/fdk pull request #1542
Opened 2019-03-14 14:54 UTC by oyvindis

… form onClick to use this handler

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-03-14 15:07 UTC, markkopaas requested changes

2019-03-14 15:07 UTC, markkopaas commented on applications/registration-react/src/pages/dataset-registration-page/formsLib/formHandlerDatasetPatch.js
> +  const header = {
det skulle ikke være i bruk? også jeg tror ikke at du trenger den header når du kaller patch endepunkt i api-lag

2019-03-14 15:07 UTC, markkopaas commented on applications/registration-react/src/pages/dataset-registration-page/formsLib/formHandlerDatasetPatch.js
> +      return Promise.reject(error);
alle promisene må være håndtert. Det gjør du ikke i onclick handler
så kanksje det er bedre å ikke returnere promise (linje 38), og da må du også ikke kaste rejection her.
notere at det er motsatt av hva jeg sa i forrige kommentar 😄  
så egentlig du må returnere, men ta vare å ikke reject, hvis du vil ikke ha catch i kaller.

2019-03-14 15:07 UTC, markkopaas commented on applications/registration-react/src/pages/dataset-registration-page/formsLib/formHandlerDatasetPatch.js
> +      if (_.get(values, 'registrationStatus')) {
de if-ene skulle være i den plass hvor de er relevante. så kanskje returnere promise, og da kaller skulle ta vare av sindel av den promise chain.

2019-03-14 15:07 UTC, markkopaas commented on applications/registration-react/src/pages/dataset-registration-page/formsLib/asyncValidateDatasetInvokePatch.js
>    const datasetId = _.get(match, ['params', 'id']);
jeg håpte at vi trenger ikke å passe dataset id inni her.
Men bedre løsning enn å passe match, er hvis du passer datasetId direkte (som props)

2019-03-14 15:18 UTC, oyvindis commented on applications/registration-react/src/pages/dataset-registration-page/formsLib/formHandlerDatasetPatch.js
> +      if (_.get(values, 'registrationStatus')) {
oj, disse if-ene skal uansett ikke være med her logisk. Fjerner dem.

2019-03-14 15:27 UTC, oyvindis commented on applications/registration-react/src/pages/dataset-registration-page/formsLib/formHandlerDatasetPatch.js
> +      return Promise.reject(error);
Fjernet reject

2019-03-14 15:48 UTC, oyvindis commented on applications/registration-react/src/pages/dataset-registration-page/formsLib/formHandlerDatasetPatch.js
> +  const header = {
Ja, fjernet header fra api-lag og fra der den blir kalt.

2019-03-18 14:40 UTC, oyvindis commented on applications/registration-react/src/pages/dataset-registration-page/formsLib/asyncValidateDatasetInvokePatch.js
>    const datasetId = _.get(match, ['params', 'id']);
Ikke endret.

2019-03-18 14:49 UTC, markkopaas approved these changes

2019-03-18 14:49 UTC, markkopaas commented on applications/registration-react/src/pages/dataset-registration-page/form-accessRights/form-accessRights.component.jsx
> +    match,
må form vite noe om router? kan vi ikke sende id... Egentlig det kunen være bare en komponent (overste) som vet noe om router. Eller det kunne være decorator, så at ingen komponenter vet noe om router.

2019-03-18 14:49 UTC, markkopaas commented on applications/registration-react/src/pages/dataset-registration-page/formsLib/asyncValidateDatasetInvokePatch.js
>    const datasetId = _.get(match, ['params', 'id']);
jeg fortset håper vi kan gjøre det :)

2019-03-19 09:14 UTC, merged