Feature/mp/apistandard
Altinn/fdk pull request #1558
Opened 2019-03-18 13:48 UTC by markkopaas

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-03-19 11:08 UTC, thomasnokleby commented on applications/reference-data/src/main/resources/rdf/api-service-type-skos.ttl
> +    at:authority-code "Kundeforhold";
Her bør det nok være api-service-types

2019-03-19 11:08 UTC, thomasnokleby requested changes
Se kommentar

2019-03-19 11:12 UTC, thomasnokleby commented on applications/reference-data/src/main/resources/rdf/api-service-type-skos.ttl
> +    at:authority-code "Kontoopplysninger";
Her bør det nok være api-service-types

2019-03-20 14:53 UTC, fheitmann approved these changes

2019-03-21 07:10 UTC, merged