Fix/ois/1443 filter
Altinn/fdk pull request #1712
Opened 2019-04-15 10:41 UTC by oyvindis

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-04-16 09:13 UTC, markkopaas requested changes

2019-04-16 09:13 UTC, markkopaas commented on applications/search/src/pages/search-page/search-page.jsx
> +  let datasetSearchParams = '';
locationsearch er parsed params, så typ er Map eller Object, ikke string

2019-04-16 09:13 UTC, markkopaas commented on applications/search/src/pages/search-page/search-page.jsx
> +    datasetSearchParams = locationSearch;
det ser ut at du har betingelse og alternativ. men alternativ ligger helt borte, og også har feil type. 
kankskje:
```
datasetSearchParams=(location.pathname === PATHNAME_DATASETS)? locationSearch:{}
```

2019-04-17 10:03 UTC, markkopaas approved these changes

2019-04-23 08:12 UTC, oyvindis commented on applications/search/src/pages/search-page/search-page.jsx
> +  let datasetSearchParams = '';
rettet

2019-04-23 08:12 UTC, oyvindis commented on applications/search/src/pages/search-page/search-page.jsx
> +    datasetSearchParams = locationSearch;
rettet

2019-04-23 08:13 UTC, merged