fix (search-api): Fix for Issue #1756 OAlso filter documents based on…
Altinn/fdk pull request #1775
Opened 2019-05-07 10:41 UTC by thomasnokleby

… the sub-LOS themes

Reelt sett: Ikke bare søke etter "Arbeid" men alle undertagsene under arbeid også.

2019-05-07 13:59 UTC, markkopaas requested changes
fiks refernce-data url config

2019-05-07 14:03 UTC, markkopaas commented
kan du forklare, hvorfor må query ekspanderes på denne måte? kan vi ikke ha alt ekspansjon på indekseringstid, så at søke kunne være enkelt? (som vi indekser path med alle overste nivåer)?

elastic gjør begge data processing (som indekser) men også er i query (analyzer). Kanskje det er noe vi kan gjøre i analyze, sån et søke kunne matche?

2019-05-08 12:07 UTC, markkopaas requested changes

2019-05-08 12:07 UTC, markkopaas commented on applications/search-api/src/main/resources/application.yml
> +  referenceDataUrl: ${referenceDataUrl:http://reference-data:8080}
skulle være bare: "http://reference-data:8080" fordi i prod er det alltid lokal vm-nettverk.

2019-05-08 12:07 UTC, markkopaas commented on applications/search-api/src/main/resources/application.yml
> +  referenceDataUrl: http://localhost:8113
vi må tenke på utvikler-experince her. Vi snakket, at typisk utvinglingsprocess er bare en microservice en gang. derfor, alle tjenestene skulle peke på docker som default. Men noen ganger, hvis man utvikler samtidlig to tjenester, da kan det være fornuftig å kjøre begge i intellij (i host). 

Derfor anbefaler jeg å kommentere ut den spesialsituasjon.
```
referenceDataUrl: http://localhost:8112 #http://localhost:8113
```

2019-05-09 06:07 UTC, thomasnokleby commented on applications/search-api/src/main/resources/application.yml
> +  referenceDataUrl: ${referenceDataUrl:http://reference-data:8080}
fixed

2019-05-09 06:07 UTC, thomasnokleby commented on applications/search-api/src/main/resources/application.yml
> +  referenceDataUrl: http://localhost:8113
fixed

2019-05-09 06:33 UTC, merged