chore(search): refactor filter-tree to use hooks
Altinn/fdk pull request #1799
Opened 2019-05-10 12:20 UTC by oyvindis

Jira issue link: [link](LINK_HERE)

> check applicable boxes

- [ ] I have made tests to match the user stories
- [ ] This code does not require tests that match user stories

2019-05-12 09:23 UTC, markkopaas requested changes

2019-05-12 09:23 UTC, markkopaas commented on applications/search/src/pages/search-page/filter-tree/filter-tree.component.jsx
> +  const { state, toggleFilter, toggleList } = useFilterTreeState();
https://reactjs.org/docs/hooks-state.html#tip-using-multiple-state-variables

du kan ha flere state, trenger ikke å være en stor state object
```
  const [openFiter, setOpenFilter] = useState(true);
  const [openList, setOpenList] = useState(false);
```

2019-05-16 08:20 UTC, oyvindis commented on applications/search/src/pages/search-page/filter-tree/filter-tree.component.jsx
> +  const { state, toggleFilter, toggleList } = useFilterTreeState();
Endret

2019-05-16 08:34 UTC, markkopaas approved these changes

2019-05-16 10:42 UTC, merged