feat(search) Filter out NAP data for datasets.
Altinn/fdk pull request #2270
Opened 2019-09-10 08:09 UTC by skobba

2019-09-10 08:18 UTC, oyvindis commented on applications/search/src/api/datasets.js
> +    { ...query, accessrights, theme, aggregations: searchAggregations },
theme skal være 'losTheme'. 'theme' er det filteret som er under utfasing.

2019-09-10 08:27 UTC, oyvindis commented on applications/search/src/api/datasets.js
> +  // Filter out NAP data if filterTransportDatasets = true in localstorage
Forslag:
Hvis du har en egen funksjon under /lib som heter f.eks. 'addQueryFiltersIfNap' som returnerer objekt {losTheme: 'TRAN', accessrights: 'PUBLIC'}, så sjekker du mot config her om du skal returnere denne eller bare undefined.

Da kan du her bare si query = Object.assign(query, addQueryFiltersIfNap);

Blir renere kode hvis det fungerer.

2019-09-10 10:13 UTC, markkopaas commented on applications/search/src/api/datasets.js
> +    { ...query, accessrights, theme, aggregations: searchAggregations },
oi, her skal vi få konflikt med min bransje

2019-09-10 10:21 UTC, markkopaas requested changes

2019-09-10 10:21 UTC, markkopaas commented on applications/search/src/api/datasets.js
> +export const datasetsSearchUrl = query => {
etter #2262 har vi datasetsSearch

2019-09-12 06:57 UTC, markkopaas approved these changes

2019-09-12 06:57 UTC, markkopaas commented on applications/search/src/api/datasets.js
> +  return axios(datasetsUrlBase, { params }).then(r => r.data);
vi kan komme tibake til "enlinje" sånn

```
export const datasetsSearch = params => 
  axios(datasetsUrlBase, { params:{...params,...napFilterIfNeeded() }).then(r => r.data);
```

2019-09-12 11:59 UTC, merged