Fix/az/sources bugs
Altinn/fdk pull request #2283
Opened 2019-09-10 15:34 UTC by azaxarov

2019-09-12 13:33 UTC, markkopaas requested changes

2019-09-12 13:33 UTC, markkopaas commented on applications/search/src/l10n/nn.json
> +    "basertPåKilde": "Basert på",
Endringene i tekstene passer ikke sammen med din kommitmelding. Det som et eget mål

2019-09-12 13:33 UTC, markkopaas commented on applications/search/src/pages/concept-details-page/concept-details-page.jsx
> +    sourceRelationship !== 'egendefinert' &&
fordi du har "early exit", da trenger du ikke, teknisk, o sjekke det igjen her.

2019-09-12 13:33 UTC, markkopaas commented on applications/search/src/pages/concept-details-page/concept-details-page.jsx
> +    sourceRelationship !== 'egendefinert' &&
kanskje har en til "eaarly exit"  til if(!sourceRelationship) i begynnelse, da kan du fjerne hele if  rundt av den som blir "default strategi"

2019-09-13 06:56 UTC, azaxarov commented on applications/search/src/l10n/nn.json
> +    "basertPåKilde": "Basert på",
Flyttet til egen commit

2019-09-13 07:23 UTC, azaxarov commented on applications/search/src/pages/concept-details-page/concept-details-page.jsx
> +    sourceRelationship !== 'egendefinert' &&
Enig, fikser

2019-09-13 07:50 UTC, markkopaas commented on applications/search/src/pages/concept-details-page/concept-details-page.jsx
> +    !!sources.length && (
mulighet å ha enkel early exit frea dette å

2019-09-13 07:51 UTC, markkopaas approved these changes
veldig fint nå!

2019-09-13 08:05 UTC, azaxarov commented on applications/search/src/pages/concept-details-page/concept-details-page.jsx
> +    !!sources.length && (
Fixed

2019-09-13 08:09 UTC, merged