chore: (registration-api) Whitelisted Entur AS for registration of da…
Altinn/fdk pull request #2381
Opened 2019-09-20 13:14 UTC by bgrova

…tasets

2019-09-20 13:39 UTC, stigbd approved these changes
I have no intimate knowledge of this, but it seems very ok too me (famous last words).

2019-09-20 19:38 UTC, markkopaas requested changes

2019-09-20 19:38 UTC, markkopaas commented on applications/registration-api/src/main/resources/application.yml
> +    includedOrgnr: 974760673,920210023,938275130,917422575
men det er ikke i bruk jo lenger?  noen har glemt å slette fra her.

riktig sted å gi brukere å logge seg på, er i user-api miljøvariablene ORGNR_WHITELIST og ORGFORM_WHITELIST

2019-09-23 22:48 UTC, markkopaas commented
problem var løst

2019-09-23 22:48 UTC, closed without merging