feat(search): #2339 hide eu-theme filter if only 'ukjent'
Altinn/fdk pull request #2385
Opened 2019-09-23 07:54 UTC by oyvindis

2019-09-23 22:48 UTC, markkopaas requested changes

2019-09-23 22:48 UTC, markkopaas commented on applications/search/src/pages/search-page/results-dataset/results-dataset.component.jsx
> +    buckets &&
vil du vise hvis det er ingen buckets?

2019-09-24 06:28 UTC, oyvindis commented on applications/search/src/pages/search-page/results-dataset/results-dataset.component.jsx
> +    buckets &&
Rettet, lagt på early exit if null

2019-09-24 10:39 UTC, markkopaas commented on applications/search/src/pages/search-page/results-dataset/results-dataset.component.jsx
> +    buckets &&
Hva med dette?

const showEUThemeFilter = ({buckets})=> buckets && buckets.length>1 && buckets[0].key !=='Ukjent'

2019-09-24 12:21 UTC, oyvindis commented on applications/search/src/pages/search-page/results-dataset/results-dataset.component.jsx
> +    buckets &&
buckets && buckets.length>1 && buckets[0].key !=='Ukjent' -> Dvs. du har eu-tema aggregering med andre temaer som ikke er 'Ukjent'. Da skal filter for EU-tema vises, funksjonen returnerer 'true'. Bare hvis eneste EU-tema er 'Ukjent' så skal ikke filter for EU-tema vises. Lagt til test.

2019-09-24 14:30 UTC, markkopaas commented on applications/search/src/pages/search-page/results-dataset/results-dataset.component.jsx
> +    buckets &&
fin test! :) 
din kode er fint nåkk, kan merge.
men her er tilsvarende oneliner:
```
export const showEUThemeFilter = ({ buckets }) =>
  buckets &&
  buckets.length > 0 &&
  !(buckets.length === 1 && buckets[0].key === 'Ukjent');
```

2019-09-24 14:31 UTC, markkopaas approved these changes

2019-09-25 08:16 UTC, merged