Fix/ois/2386 nap
Altinn/fdk pull request #2411
Opened 2019-09-25 10:38 UTC by oyvindis

2019-09-25 22:11 UTC, markkopaas requested changes
bare fix index.ejs, resten kan ignoreres eller gjøres separat

2019-09-25 22:11 UTC, markkopaas commented on applications/search/src/app/app-nav-bar/app-nav-bar.jsx
> +              href="/"
er det god ide å ha full refresh? prøv Link? det kan være også en ant commit, fordi det er ikke om nap

2019-09-25 22:11 UTC, markkopaas commented on applications/search/src/app/app.jsx
> +      <DocumentMeta {...meta} />
jeg ser ikke noe feil å ha title rett her. litt kortere. ikke viktig

2019-09-25 22:11 UTC, markkopaas commented on applications/search/src/index.html
> +		if (location.hostname.indexOf("nap.") >= 0) {
du glemte index.ejs.

eller vil du kanskje bevege search til nginx :) da blir det bare ett index.html

2019-09-26 07:41 UTC, oyvindis commented on applications/search/src/app/app.jsx
> +      <DocumentMeta {...meta} />
Rettet

2019-09-26 07:44 UTC, oyvindis commented on applications/search/src/index.html
> +		if (location.hostname.indexOf("nap.") >= 0) {
samme endring i index.ejs

Noterer det andre i backlog

2019-09-26 07:45 UTC, oyvindis commented on applications/search/src/app/app-nav-bar/app-nav-bar.jsx
> +              href="/"
Notert i backlog.

2019-09-26 07:48 UTC, markkopaas approved these changes

2019-09-26 08:06 UTC, merged