chore(registration-react): #2446 validation of form-title with yup
Altinn/fdk pull request #2526
Opened 2019-10-10 10:40 UTC by oyvindis

2019-10-10 13:02 UTC, markkopaas requested changes

2019-10-10 13:02 UTC, markkopaas commented on applications/registration-react/package.json
> +    "whatwg-fetch": "^3.0.0",
sikkert en ant pr, men trenger vi faktisk fetch nå?

2019-10-10 13:02 UTC, markkopaas commented on applications/registration-react/src/lib/unFlattenObject.js
> +const setValue = (object, path, value) => {
det ser ut som en library kode? kan du ikke import dette?

2019-10-10 13:02 UTC, markkopaas commented on applications/registration-react/src/pages/dataset-registration-page/form-title/configured-form-title.jsx
> +  validate: values => {
slik valideringstrategi ser ikke ut spesifikk til dette felte. kan du bevege til lib?

2019-10-10 13:17 UTC, oyvindis commented on applications/registration-react/package.json
> +    "whatwg-fetch": "^3.0.0",
antar vi ikke trenger det, men må fjerne det i annen pr.

2019-10-10 13:40 UTC, oyvindis commented on applications/registration-react/src/lib/unFlattenObject.js
> +const setValue = (object, path, value) => {
ja, importerer lodash/set

2019-10-10 13:54 UTC, oyvindis commented on applications/registration-react/src/pages/dataset-registration-page/form-title/configured-form-title.jsx
> +  validate: values => {
lagt i lib

2019-10-11 07:01 UTC, markkopaas commented on applications/registration-react/src/lib/normalize-yup-validation.js
> +import { unFlattenObject } from './unFlattenObject';
Bra oppdeling til modul, men jeg tror ikke at normalize er en bra navnprefix. Vanligvis normalize mener jo at hvis f.e. data kommmer fra forskjellige kilder, da må man convertere de til felles "normal" struktur.

Det ser ut til meg, at her du gjør yup validation. Så, kanskje yupValidation, yupValidate, eller yupSchemaValidate, eller kanskje validate(yupSchema, values)

2019-10-11 07:02 UTC, markkopaas approved these changes
alt er bra, men jeg liker ikke modulnavn :)

2019-10-11 08:19 UTC, merged