Refactor application config values
Altinn/fdk pull request #2567
Opened 2019-10-24 10:29 UTC by NilsOveTen

2019-10-24 22:21 UTC, markkopaas requested changes

2019-10-24 22:21 UTC, markkopaas commented on applications/user-api/src/main/java/no/fdk/userapi/AltinnUserService.java
> +        return Arrays.asList(applicationValues.getOrgNrWhitelist().split(","));
nå har vi faktisk mulighet å gjøre enkelt prosessering i ApplicationValues class. Du kan bevege alle de tre listene der. - getOrgNrWhitelist getOrgFormWhitelist, getAdminListString

2019-10-24 22:21 UTC, markkopaas commented on applications/user-api/src/main/java/no/fdk/userapi/UsersController.java
> +    private AltinnUserService altinnUserService;
fint at du fant det!

2019-10-24 22:23 UTC, markkopaas requested changes
Veldig bra!
du må fikse commit melding til å følge conventional commits:
refactor(sso): refactor application config values

2019-10-25 06:21 UTC, markkopaas approved these changes
convertion *Properties

2019-10-25 06:21 UTC, markkopaas commented on applications/user-api/src/main/java/no/fdk/userapi/configuration/ApplicationValues.java
> +public class ApplicationValues {
Jeg tror det er convention å bruke Properties som suffix. En lignende eksempel er ResourceServerProperties

2019-10-25 06:46 UTC, NilsOveTen commented on applications/user-api/src/main/java/no/fdk/userapi/configuration/ApplicationValues.java
> +public class ApplicationValues {
ac37ddb
Endret i tillegg litt på strukturen i application.yml, ok?

2019-10-25 07:36 UTC, merged