feat(registration-react): added splitt login for read/write users
Altinn/fdk pull request #2589
Opened 2019-10-29 15:10 UTC by skobba

2019-10-30 06:24 UTC, markkopaas requested changes

2019-10-30 06:24 UTC, markkopaas commented on applications/registration-react/src/config.js
> +import axios from "axios";
lint

2019-10-30 06:24 UTC, markkopaas commented on applications/registration-react/src/config.js
> +  Object.assign(env, {
ikke kommit dev kode

2019-10-30 06:24 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +          Her kan du lese om datasettbeskrivelser for din virksomhet.
tekstene må leses fra l10n. også vi må slette engelsk frasfil (eget commit/pr), så at det blir ikke ekstra oversetting.

2019-10-30 06:24 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +        <p class="">
hva mener class i react?

2019-10-30 06:24 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.jsx
> -                    {localization.catalogs.missingCatalogs.accessText}
hvis du fjerner/endrer localization reference, må du også slette fra localization

2019-10-30 06:24 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.scss
> +} /* end min-width : 320px */
er det endring? lint?

2019-10-30 06:28 UTC, oyvindis commented on applications/registration-react/src/config.js
> +import axios from "axios";
config.js skulle ikke være med?
Prettier-regel sier forresten single-quote: true, hvordan blir det gjort om her?

2019-10-30 07:58 UTC, azaxarov requested changes

2019-10-30 07:58 UTC, azaxarov commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                <>
Unnecessary wrapper

2019-10-30 08:44 UTC, skobba commented on applications/registration-react/src/config.js
> +import axios from "axios";
Ok

2019-10-30 08:44 UTC, skobba commented on applications/registration-react/src/config.js
> +  Object.assign(env, {
Ok

2019-10-30 09:30 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +        <p class="">
Oppdatert med "ml-4"

2019-10-30 09:31 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                <>
Fjernet.

2019-10-30 09:47 UTC, skobba commented on applications/registration-react/src/config.js
> +import axios from "axios";
VS Code sin extension. Fixet.

2019-10-30 11:19 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +          Her kan du lese om datasettbeskrivelser for din virksomhet.
Ok.

2019-10-30 11:36 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.scss
> +} /* end min-width : 320px */
Ja, fjernet en space.

2019-10-30 13:32 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                    Les hvordan du får tilgang til å registrere og redigere
localize

2019-10-30 13:35 UTC, markkopaas requested changes
fortsett litt linting og localization

2019-10-30 13:35 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                    {' '}
er det viktig?

2019-10-30 13:35 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                    {localization.app.loginPage.postamble3}{' '}
trenger mellomrom eller?

2019-10-30 13:35 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.scss
> +@import "../../../node_modules/designsystemet/fdk-designsystem-bootstrap4/scss/colors.scss";
linting igjen

2019-10-30 13:35 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.scss
> +@media only screen and (min-width: 320px) {
hvis du må gjøre lintiung, da gjøre det i separat commit.  her kan du reversere de biter

2019-10-30 14:11 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                    Les hvordan du får tilgang til å registrere og redigere
Ok

2019-10-30 14:11 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                    {' '}
Ja, space between text.

2019-10-30 14:12 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                    {localization.app.loginPage.postamble3}{' '}
Ja, space between text.

2019-10-30 14:12 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.scss
> +@import "../../../node_modules/designsystemet/fdk-designsystem-bootstrap4/scss/colors.scss";
Korrigert.

2019-10-30 14:13 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.scss
> +@media only screen and (min-width: 320px) {
Korrigert, vet ikke hvorden det kom med.

2019-10-30 16:55 UTC, markkopaas commented on applications/registration-react/src/l10n/nb.json
> +        "description3": {
siden det er ikke brukerinput, er det lov å ha html. i teksten.
Hvis du bestemmer å bruke det, er dt best å reflektere det også i fras-navn

https://reactjs.org/docs/dom-elements.html

```
<div dangerouslySetInnerHTML={{__html:localizaition.zzz.xxxYyyHtml}} />
```

2019-10-30 16:59 UTC, markkopaas requested changes

2019-10-30 16:59 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +              {showLoginReadOnly && (
featuretoggle må fjerne den hele blokk, ikke bare knapp. teste utseende uten feature toggle på. Det er mulig at vi må leve lenge uten den freature. Vi er fortsett langt fra å være klar.

2019-10-30 16:59 UTC, markkopaas commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                    {' '}
det vil jeg se 😄 <p> begynner jo nytt line

2019-10-31 07:24 UTC, skobba commented on applications/registration-react/src/l10n/nb.json
> +        "description3": {
Ser ikke ut som noen har brukt html i json-språkfiler til nå.

2019-10-31 07:43 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +              {showLoginReadOnly && (
Ok, endret blokk.

2019-10-31 08:41 UTC, markkopaas approved these changes

2019-10-31 08:46 UTC, azaxarov approved these changes

2019-10-31 08:53 UTC, skobba commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                    {' '}
Korrigert :)

2019-11-04 10:53 UTC, oyvindis commented on applications/registration-react/src/pages/login-page/login-page.jsx
> +                      {localization.app.loginPage.readUser.description3.click}{' '}
alternativt til {' '} kan du også bruke &nbsp; (non-breaking space)

2019-11-04 10:55 UTC, oyvindis commented on applications/registration-react/src/pages/login-page/login-page.scss
> +    border-color: transparent;
Er det samme som border: none;

2019-11-04 10:57 UTC, oyvindis approved these changes
Approved, bare to kommentarer på alternativ måter å gjøre det på.

2019-11-04 11:44 UTC, merged