fix(registration-api): #2599 fix endpoint permission requirements
Altinn/fdk pull request #2603
Opened 2019-11-02 09:11 UTC by markkopaas

2019-11-04 06:49 UTC, oyvindis approved these changes

2019-11-05 09:37 UTC, azaxarov requested changes

2019-11-05 09:37 UTC, azaxarov commented on applications/registration-api/src/main/java/no/dcat/configuration/FdkPermissionEvaluator.java
> +    public FdkPermissionEvaluator(PermissionsService permissionsService) {
Lombok constructor?

2019-11-05 09:37 UTC, azaxarov commented on applications/registration-api/src/main/java/no/dcat/controller/CatalogController.java
> +    public CatalogController(CatalogRepository catalogRepository, PermissionsService permissionsService, HarvesterService harvesterService, EnhetService enhetService) {
Lombook constructor

2019-11-05 09:37 UTC, azaxarov commented on applications/registration-react/src/config.js
> +  // env.REGISTRATION_API_HOST = 'http://localhost:8115';
Is this related to this PR?

2019-11-05 12:36 UTC, markkopaas commented on applications/registration-api/src/main/java/no/dcat/configuration/FdkPermissionEvaluator.java
> +    public FdkPermissionEvaluator(PermissionsService permissionsService) {
fikset

2019-11-06 06:40 UTC, markkopaas commented on applications/registration-react/src/config.js
> +  // env.REGISTRATION_API_HOST = 'http://localhost:8115';
rebased

2019-11-06 06:40 UTC, markkopaas commented on applications/registration-api/src/main/java/no/dcat/controller/CatalogController.java
> +    public CatalogController(CatalogRepository catalogRepository, PermissionsService permissionsService, HarvesterService harvesterService, EnhetService enhetService) {
rebased

2019-11-06 06:40 UTC, markkopaas commented on applications/registration-api/src/main/java/no/dcat/configuration/FdkPermissionEvaluator.java
> +    public FdkPermissionEvaluator(PermissionsService permissionsService) {
rebased

2019-11-06 06:41 UTC, merged