fix(search): #2700 remove blank topics from search results
Altinn/fdk pull request #2743
Opened 2019-11-25 22:32 UTC by azaxarov

2019-11-26 12:04 UTC, Chlenix approved these changes

2019-11-26 13:12 UTC, markkopaas requested changes

2019-11-26 13:12 UTC, markkopaas commented on applications/search/src/components/search-hit-header/search-hit-header.component.jsx
> +              Datasettets tema.
den burde lokaliseres

2019-11-26 13:12 UTC, markkopaas commented on applications/search/src/components/search-hit-header/search-hit-header.component.jsx
> +      {(nationalComponent || theme) && !!themes.length && (
jeg tror det er bedre å samle theme-betingelsene
`
(nationalComponent || (themes && themes.lengt>0)
`

theme og themes er forvirrende, kan du bare ikke normalisere tidlig til array som input med plural navn.

2019-11-26 13:13 UTC, markkopaas commented on applications/search/src/components/search-hit-header/search-hit-header.component.jsx
> +              Datasettets tema.
i en annen pr

2019-11-26 13:30 UTC, azaxarov commented on applications/search/src/components/search-hit-header/search-hit-header.component.jsx
> +      {(nationalComponent || theme) && !!themes.length && (
Thanks!

2019-11-26 22:21 UTC, markkopaas requested changes

2019-11-26 22:21 UTC, markkopaas commented on applications/search/src/components/search-hit-header/__snapshots__/search-hit-header.component.test.jsx.snap
> +  0
dette ser ikke riktig ut. feil fixture? mangler vi proptype array check?

2019-11-27 07:55 UTC, azaxarov commented on applications/search/src/components/search-hit-header/__snapshots__/search-hit-header.component.test.jsx.snap
> +  0
Good catch, nei manglet boolean cast på array length check

2019-11-27 08:30 UTC, markkopaas approved these changes

2019-11-27 08:38 UTC, merged