Feat/ois/2757 statusbar
Altinn/fdk pull request #2798
Opened 2019-11-29 13:08 UTC by oyvindis

2019-12-02 11:01 UTC, markkopaas requested changes

2019-12-02 11:01 UTC, markkopaas commented on applications/registration-react/src/lib/registration-status.js
> +const REGISTRATION_STATUS_APPROVE = 'APPROVE';
er den ny  status begge til dataset og api?

2019-12-02 11:01 UTC, markkopaas commented on applications/registration-react/src/lib/registration-status.js
> +const REGISTRATION_STATUS_APPROVE = 'APPROVE';
det ser ut til meg at vi trenger en "domain module" til dataset. en modul som inneholder alle reglene og hjelpefunksjonene som hjelper å håntere dataset registrasjon. også selectorene i redux børde beveges der - redux store bare gir deg tilgang til object, men innehold må dekoderes videre med domain funksjoner. Det er ikke utenkelig at domain funksjonenene er i stedet klass-metodene...

2019-12-02 11:22 UTC, oyvindis commented on applications/registration-react/src/lib/registration-status.js
> +const REGISTRATION_STATUS_APPROVE = 'APPROVE';
api skal ikke ha status 'approve', er bare datasett som vil sette den.

2019-12-06 09:05 UTC, markkopaas commented on applications/registration-react/src/components/status-bar/default-dialog/default-dialog.component.jsx
> +        {type === 'dataset' && (
Akkurat her er det som jeg tenker er problem. 
I resten av koden tenker antar du at alle typene (mener api og dataset) har samme statusene, men det er her du faktisk begrenser at bare dataset kan ha en ekstra statusverdi, 'APPROVED'.  Dette er supervanskelig å finne ut, hvis du har ikke den bit av kode i hodet.
Dette skal bryte sammen ganske snart.


En forslag til bedre design.
- Ha gjenbrukbare bygge-elementene i components, og ikke-gjenbrukbare under pages
- Ikke bruk form til statusendring, i stedet bruk redux custom action

begge side (api og dataset)
burde ha sitt eget StatusBar komponent, den komponent har ikke UI. Det bare har kontol over hva slags dialog er synlig
Forskjellige dialogene kan leve i components, det er ikke sikkert så mye forskjellige.

Dialog med å status endring knapp er også forskjellige. så kan ha separarerte komponentene der - DatasetStatusDialog, og ApiStatusDialog, respektive kataloger.

På den måte kan du separare, at StatusBar i api og dataset. har forskjellige statusvalgene og dialogene.

2019-12-10 07:59 UTC, merged