feat(registration-react): add expand/collapse button
Altinn/fdk pull request #2952
Opened 2019-12-19 14:39 UTC by skobba

2019-12-19 15:32 UTC, markkopaas requested changes

2019-12-19 15:32 UTC, markkopaas commented on applications/registration-react/src/components/form-template/form-template.component.jsx
> +  useEffect(() => {
hvis du allerede bruker useEffect, da kan du bruke jo useState og fjerne recompose state dekoratorene

2019-12-20 09:49 UTC, oyvindis commented on applications/registration-react/src/pages/dataset-registration-page/dataset-registration-page-pure.tsx
> +      <div class="row">
Må stå 'className'

2019-12-20 09:51 UTC, oyvindis commented on applications/registration-react/src/pages/dataset-registration-page/dataset-registration-page-pure.tsx
> +        <div class="col">
Må bruker 'className'. Men 'col' er ikke noe, og er unødvendig hvis den uansett skal være col-12. Alternativt til å bruker float på child-element, kan du bruke flex-properties,  'd-flex' og 'justify-content-end'.

2019-12-20 09:51 UTC, skobba commented on applications/registration-react/src/pages/dataset-registration-page/dataset-registration-page-pure.tsx
> +      <div class="row">
Ok

2019-12-20 09:52 UTC, oyvindis approved these changes
Bra, approved! Men se kommentar, du må bare rette 'class' til 'className'.

2019-12-20 10:42 UTC, skobba commented on applications/registration-react/src/pages/dataset-registration-page/dataset-registration-page-pure.tsx
> +        <div class="col">
Ok, bruker: d-flex justify-content-end

2019-12-20 10:42 UTC, merged